---
title: "Choropleth Maps"
format:
  html: default
editor_options: 
  chunk_output_type: inline
---

```{r}
#| include: false

library(maps)
library(tidyverse)
library(mdsr) 
library(sf)
library(poliscidata) 
library(viridis)
```

```{r}
#| message: false
#| warning: false
#| include: false

# Get info to draw US states for geom_polygon (connect the lat-long points)
library(maps)
states_polygon <- as_tibble(map_data("state")) |>
  select(region, group, order, lat, long)

# See what the state (region) levels look like in states_polygon
unique(states_polygon$region)


# Get info to draw US states for geom_sf and leaflet (simple features object 
#   with multipolygon geometry column)
library(sf)
states_sf <- 
  read_sf("https://rstudio.github.io/leaflet/json/us-states.geojson") |>
  select(name, geometry)

# See what the state (name) levels look like in states_sf
unique(states_sf$name)


# Load in state-wise data for filling our choropleth maps
#   (Note that I selected my two variables of interest to simplify)
library(poliscidata)   # may have to install first
polisci_data <- as_tibble(poliscidata::states) |>
  select(state, abort_rate08, gay_support3)

# See what the state (state) levels look like in polisci_data
unique(polisci_data$state)   # can't see trailing spaces but can see
                             #   lack of internal spaces
print(polisci_data)   # can see trailing spaces

# Make sure all keys have the same format before joining:
#   all lower case, no internal or external spaces

polisci_data <- polisci_data |>
  mutate(state = str_trim(str_to_lower(state)))

states_polygon <- states_polygon |>
  mutate(region = str_remove_all(region, "\\s"))

states_sf <- states_sf |>
  mutate(state = str_remove_all(str_to_lower(name), "\\s"))


# Now we can merge data sets together for the static and the interactive plots


# Merge with states_polygon (static)

state_map <- polisci_data |>
  right_join(states_polygon, by = c("state" = "region"))

# Check that merge worked for 48 contiguous states
polisci_data |>
  anti_join(states_polygon,  by = c("state" = "region"))

states_polygon |>
  anti_join(polisci_data, by = c("region" = "state"))


# Merge with states_sf (static or interactive)

states_sf <- states_sf |>
  right_join(polisci_data)

# Check that merge worked for 48 contiguous states

polisci_data |>
  anti_join(states_sf)
states_sf |>
  anti_join(polisci_data)


```

Here we have some

Numeric variable (static plot):

```{r}
state_map |>
  ggplot(mapping = aes(x = long, y = lat, group = group)) +
  geom_polygon(aes(fill = abort_rate08 ), color = "black", linewidth = 0.2) +
  coord_map() + 
  theme_void() + 
  scale_fill_viridis() +
  labs(fill = "Abortion Rate Per 1000  ",
       title = "  Abortion Rate in US States 2008") 

```

Numeric variable (interactive plot):

```{r}
#| eval: false

bins <- c(0, 5, 10, 20, 30, 40, 50)
pal <- colorBin("YlOrRd", domain = states_sf$abort_rate08, bins = bins)

states_sf <- states_sf |>
  mutate(labels = str_c(name, ": ", states_sf$abort_rate08, " per 1000 Women"))

labels <- lapply(states_sf$labels, HTML)

leaflet(states_sf) |>
  setView(-96, 37.8, 4) |>
  addTiles() |>
  addPolygons(
    fillColor = ~pal(abort_rate08),
    weight = 2,
    opacity = 1,
    color = "white",
    dashArray = "12",
    fillOpacity = 0.5,
    highlightOptions = highlightOptions(
      weight = 3,
      color = "#666",
      dashArray = "0.1",
      fillOpacity = 0.9,
      bringToFront = TRUE),
    label = labels,
    labelOptions = labelOptions(
      style = list("font-weight" = "normal", padding = "3px 8px"),
      textsize = "15px",
      direction = "auto")) |>
  addLegend(pal = pal, values = ~abort_rate08, opacity = 0.7, title = NULL,
    position = "bottomright")
```

Categorical variable (static plot):

```{r}
state_map |>
  filter(state != "districtofcolumbia") |>
  ggplot(mapping = aes(x = long, y = lat, group = group)) +
  geom_polygon(aes(fill = gay_support3 ), color = "black", linewidth = 0.2) +
  coord_map() + 
  theme_void() + 
  scale_fill_manual(values = c("#bb97f7", "#8b48fa", "#6002fa")) +
  labs(fill = "Level of Agreement   ",
       title = "   Support of Gay marriage in US states") 
```

Categorical variable (interactive plot):

```{r}
#| eval: false

pal <- colorFactor(c("#bb97f7", "#8b48fa", "#6002fa"), domain = states_sf$gay_support3)

states_sf <- states_sf |>
  mutate(labels = str_c(name, ": ", states_sf$gay_support3))

labels <- lapply(states_sf$labels, HTML)

leaflet(states_sf) |>
  setView(-96, 37.8, 4) |>
  addTiles() |>
  addPolygons(
    fillColor = ~pal(gay_support3),
    weight = 2,
    opacity = 1,
    color = "white",
    dashArray = "12",
    fillOpacity = 0.8,
    highlightOptions = highlightOptions(
      weight = 3,
      color = "#666",
      dashArray = "0.1",
      fillOpacity = 0.9,
      bringToFront = TRUE),
    label = labels,
    labelOptions = labelOptions(
      style = list("font-weight" = "normal", padding = "3px 8px"),
      textsize = "15px",
      direction = "auto")) |>
  addLegend(pal = pal, values = ~gay_support3, opacity = 0.7, title = NULL,
    position = "bottomright")
```
